insert into public.rag_documents (
    doc_type,
    title,
    summary,
    content,
    source_label,
    source_url,
    source_tone,
    verification_status,
    venue_name,
    topic_id,
    tags,
    metadata
)
values
(
    'venue',
    'Journal of the Learning Sciences',
    '저널 · Learning Sciences · 공식 링크 확인',
    'Journal of the Learning Sciences는 학습과학 분야의 대표 저널입니다. 학습의 인지적, 사회적, 설계적 측면을 다루며 CSCL, cognition, learning environments, educational design과 자주 연결됩니다. 앱 내 참고 등급은 Q1이며, 설명은 편집 요약과 공식 링크를 함께 참고해야 합니다.',
    'Journal of the Learning Sciences · 저널 · 공식 링크 확인',
    'https://www.tandfonline.com/toc/hlns20/current',
    'official',
    'reference',
    'Journal of the Learning Sciences',
    null,
    array['journal', 'learning-sciences', 'cscl'],
    '{"seed":"v1"}'::jsonb
),
(
    'venue',
    'International Journal of Computer-Supported Collaborative Learning',
    '저널 · CSCL · 공식 링크 확인',
    'International Journal of Computer-Supported Collaborative Learning은 CSCL 핵심 저널입니다. collaborative learning, discourse analysis, group cognition, knowledge building과 자주 연결됩니다. 입문자에게는 CSCL 대표 venue로 안내하기 좋습니다.',
    'International Journal of Computer-Supported Collaborative Learning · 저널 · 공식 링크 확인',
    'https://www.springer.com/journal/11412',
    'official',
    'reference',
    'International Journal of Computer-Supported Collaborative Learning',
    null,
    array['journal', 'cscl', 'collaboration'],
    '{"seed":"v1"}'::jsonb
),
(
    'venue',
    'Computers & Education',
    '저널 · TEL · 공식 링크 확인',
    'Computers & Education은 technology-enhanced learning의 대표 저널입니다. 실증 연구 비중이 높고 educational technology, e-learning, learning analytics와 자주 연결됩니다. 비교 질문에서 자주 회수되는 핵심 venue입니다.',
    'Computers & Education · 저널 · 공식 링크 확인',
    'https://www.sciencedirect.com/journal/computers-and-education',
    'official',
    'reference',
    'Computers & Education',
    null,
    array['journal', 'tel', 'learning-analytics'],
    '{"seed":"v1"}'::jsonb
),
(
    'venue',
    'Learning Analytics and Knowledge Conference',
    '학회 · Learning Analytics · 공식 링크 확인',
    'LAK는 Learning Analytics and Knowledge 분야의 대표 학회입니다. 데이터 기반 학습 분석, dashboard, prediction, learner support와 관련됩니다. CFP 질문과 입문 경로 추천에서 함께 제시하기 좋습니다.',
    'Learning Analytics and Knowledge Conference · 학회 · 공식 링크 확인',
    'https://www.solaresearch.org/events/lak/lak26/general-call/',
    'official',
    'official',
    'Learning Analytics and Knowledge Conference',
    null,
    array['conference', 'lak', 'learning-analytics', 'cfp'],
    '{"seed":"v1"}'::jsonb
),
(
    'venue',
    'International Conference on Artificial Intelligence in Education',
    '학회 · AIED · 공식 링크 확인',
    'AIED는 인공지능 기반 교육 연구를 다루는 대표 학회입니다. adaptive systems, intelligent tutoring systems, generative AI, personalization과 연결됩니다. 공식 CFP 일정은 별도 검증 레코드와 함께 확인하는 것이 좋습니다.',
    'International Conference on Artificial Intelligence in Education · 학회 · 공식 링크 확인',
    'https://aied-conference.org/2026/call-for-paper',
    'official',
    'official',
    'International Conference on Artificial Intelligence in Education',
    null,
    array['conference', 'aied', 'ai-in-education', 'cfp'],
    '{"seed":"v1"}'::jsonb
),
(
    'topic',
    'CSCL',
    '연구 주제 · 협력 학습',
    'CSCL은 Computer-Supported Collaborative Learning의 약자입니다. 디지털 도구를 활용해 협력 학습을 설계하고 분석하는 분야이며, IJCSCL, ISLS, ICLS와 자주 연결됩니다. 입문자에게는 대표 저널과 학회를 함께 보여주는 것이 좋습니다.',
    'CSCL · 연구 주제',
    null,
    'editorial',
    'reference',
    null,
    'argumentation-and-learning-in-cscl',
    array['topic', 'cscl', 'collaboration'],
    '{"seed":"v1"}'::jsonb
),
(
    'topic',
    'Learning Analytics',
    '연구 주제 · 데이터 기반 학습 분석',
    'Learning Analytics는 학습 데이터를 분석해 학습과 교수 설계를 개선하는 분야입니다. LAK, Journal of Learning Analytics, EDM과 자주 연결되며, dashboard, prediction, learner support, feedback이 주요 하위 질문입니다.',
    'Learning Analytics · 연구 주제',
    null,
    'editorial',
    'reference',
    null,
    'analytics-for-learning-and-teaching',
    array['topic', 'learning-analytics', 'edm'],
    '{"seed":"v1"}'::jsonb
),
(
    'glossary',
    'CFP',
    '용어 안내 · 학회 논문 모집 공고',
    'CFP는 Call for Papers의 약자입니다. 실제 사용 시 주 마감일, abstract deadline, notification, camera-ready 일정을 함께 확인해야 하며, 공식 링크와 마지막 검증일을 같이 보는 것이 중요합니다.',
    'CFP · 용어 안내',
    null,
    'reference',
    'reference',
    null,
    null,
    array['glossary', 'cfp', 'deadline'],
    '{"seed":"v1"}'::jsonb
),
(
    'glossary',
    'Quartile 참고 등급',
    '용어 안내 · Q1~Q4 참고 지표',
    'Q1~Q4는 저널의 상대적 구간을 뜻하지만 제공원과 시점에 따라 달라질 수 있습니다. 이 앱에서는 참고용 지표로 취급하며, 공식 source-of-truth를 직접 대체하지 않습니다.',
    'Quartile 참고 등급 · 용어 안내',
    null,
    'reference',
    'reference',
    null,
    null,
    array['glossary', 'quartile', 'q1'],
    '{"seed":"v1"}'::jsonb
)
on conflict do nothing;
